version: '3'

services:
  wpss:
    platform: linux/amd64
    build: .
    ports:
      - "50690:50690"
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: '3.0'
